### PR TITLE
Support Python 3.7

### PR DESCRIPTION
**Pull request by shinoys222**
Replace async Keyword with is_async to support python 3.7

### CODE REVIEW

**Review by renanrv — APPROVED** [review]

**Comment by shinoys222** [comment]
Closes issue - https://github.com/checkr/pyflagr/issues/2

**Comment by noraiz-anwar** [comment]
@shinoys222 Thanks for the fix.
@zhouzhuojie Could you please review and merge this request? This is a blocker for everyone who wants to use this on Python 3.7.
Thanks in anticipation.

**Comment by arrase** [comment]
Could you please review and merge this request? Thanks in anticipation.

**Comment by zhouzhuojie** [comment]
Is it generated from the latest `swaggerapi/swagger-codegen-cli` docker image? I ran and saw the change like:

```
-        if kwargs.get('async'):
+        if kwargs.get('async_req'):
```

How about https://github.com/checkr/pyflagr/pull/8

**Comment by zhouzhuojie** [comment]
Thanks for the PR. I've updated the latest version of swagger.yaml and regenerate the python SDK via https://github.com/checkr/pyflagr/pull/8.

**Pull request closed without merging**
